name: Project setup
description: Set up Node, and cache the pnpm store.

inputs:
  runs-on:
    description: Optional runner label to use for cache key (falls back to runner.os)
    required: false
  node-version:
    description: Node version to use (required)
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        cache: true
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
